### ISSUE TITLE
协调前端和后端交互

### ISSUE THREAD

**Issue by Eadral** [BUAANameNotFound/OCR-Form-Tools#34]

**Comment by xiaomaoaichiyu** [comment]
目前后端实现了http请求中body的json文件的读取！下一步：配合前端需求！

**Comment by xiaomaoaichiyu** [comment]
和前端配合，实现了前端的json文件的存放，下一步，后端生成数据模块的集成！

**Comment by xiaomaoaichiyu** [comment]
修改Http，json文件和pdf文件传送分别为一个Azure Function，数据生成为一个GET的Azure Fucntion，下载数据为一个Azure Function

**Comment by xiaomaoaichiyu** [comment]
DownLoad: https://lyniupi.azurewebsites.net/api/DownLoad
  Generate: https://lyniupi.azurewebsites.net/api/Generate
  UpLoadJson: https://lyniupi.azurewebsites.net/api/UpLoadJson
  UpLoadPdf: https://lyniupi.azurewebsites.net/api/UpLoadPdf

**Comment by xiaomaoaichiyu** [comment]
四个分别是上传json，上传pdf，生成，下载pdf，如果生成出了问题，那可能是生成规则没有考虑到或者是路径问题，欢迎反馈

用法的话，上传都是POST，json就是直接放在http的请求里面，pdf上传二进制文件（bytes，utf-8）
生成用GET请求，通过参数genNum只当生成个数，下载直接Http的GET请求就好
