### ISSUE TITLE
前端：增加introduction页面

### ISSUE THREAD

**Issue by bingokunkun** [BUAANameNotFound/OCR-Form-Tools#47]
**Is your feature request related to a problem? Please describe.**
同学们不知道我们的项目是干什么的，怎么用。

**Describe the solution you'd like**
将该页面专门做成一个类似帮助页面的形式，列出我们软件的功能和使用我们软件的关键步骤

**Describe alternatives you've considered**
字太多不好看的画，或者给个使用说明书的链接？

**Comment by lzhmarkk** [comment]
@xiaomaoaichiyu 需要新版教程文档

**Comment by xiaomaoaichiyu** [comment]
更新完成
