### ISSUE TITLE
前端：修改data页面

### ISSUE THREAD

**Issue by bingokunkun** [BUAANameNotFound/OCR-Form-Tools#49]
**Is your feature request related to a problem? Please describe.**
增加了新的功能，data页面需要支持预览、下载Excel文件

**Describe the solution you'd like**
预览、下载Excel文件

**Describe alternatives you've considered**
后端可以将Excel转成PDF，则预览功能可能也不太需要大的更改

**Comment by bingokunkun** [comment]
还有HTML页面

**Comment by Eadral** [comment]
下载excel预计在predict页面实现, 即预测后导出预测结果表格
