### ISSUE TITLE
后端：文件结构更改

### ISSUE THREAD

**Issue by xiaomaoaichiyu** [BUAANameNotFound/OCR-Form-Tools#72]
文件结构匹配新功能，分别放在三个子文件夹中
-type1：放置上传的pdf空白模板
-type2：放置上传的pdf正常表单
-type3：放置生成的pdf表单

**Comment by lzhmarkk** [comment]
在训练表单时，不是只能读取一个文件夹内的数据吗，那这样分文件夹的话，怎么做到“用户自由选择需要加入训练的表单”呢？

是不是要分为两个文件夹，第一个放需要训练的表单，一个放不训练的表单，然后通过json文件的方式标注每个表单的类型呢？

**Comment by xiaomaoaichiyu** [comment]
训练的文件，现在应该是只有type3里面可以拿来直接训练.
type3里是pdf文件和对应的json文件（全部是生成的）

如果想改变，那我还是去实现这个移动的接口吧。就是我们目前而言，这个是不是重点呢？因为按照直接的思路来，训练的话，就用type3的文件就可以了。

原项目中标注训练的方法可以看作被我们放弃了，采用了这种生成的数据来训练的方式。

至于你说的是够需要移动，这个可以再商讨一下

**Comment by xiaomaoaichiyu** [comment]
如果对于前端的训练确实有必要，那我还是去实现一下。
